# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 611090a73bf204adf35ef34fe4cc6b173af30fcfbbcb3feec3b4ffabaf1f7a125494fcb904bba6e69865e67dce98f4bc960fe9e34e3d271a6f33f8bbbae72588

test:
  secret_key_base: 7aa4657931df6fee06f8040f36b40f45bd4d95c7e477be76feb143d56390124098230215a4e583b2fe73a6eefee120cfa8b2ca8076532dea20c27d0fd0c33471

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
